@extends('layouts.backend.layout')
@section('content')
<style type="text/css">
   @keyframes ldio-284ix4wfeaei {
   0% { opacity: 1 }
   50% { opacity: .5 }
   100% { opacity: 1 }
   }
   .ldio-284ix4wfeaei div {
   position: absolute;
   width: 10px;
   height: 40px;
   top: 30px;
   animation: ldio-284ix4wfeaei 1s cubic-bezier(0.5,0,0.5,1) infinite;
   }.ldio-284ix4wfeaei div:nth-child(1) {
   transform: translate(15px,0);
   background: #e15b64;
   animation-delay: -0.6s;
   }.ldio-284ix4wfeaei div:nth-child(2) {
   transform: translate(35px,0);
   background: #f47e60;
   animation-delay: -0.4s;
   }.ldio-284ix4wfeaei div:nth-child(3) {
   transform: translate(55px,0);
   background: #f8b26a;
   animation-delay: -0.2s;
   }.ldio-284ix4wfeaei div:nth-child(4) {
   transform: translate(75px,0);
   background: #abbd81;
   animation-delay: -1s;
   }
   .loadingio-spinner-bars-whv1n2lzl1 {
   width: 41px;
   height: 41px;
   display: inline-block;
   overflow: hidden;
   background: #ffffff;
   }
   .ldio-284ix4wfeaei {
   width: 100%;
   height: 100%;
   position: relative;
   transform: translateZ(0) scale(0.41);
   backface-visibility: hidden;
   transform-origin: 0 0; /* see note above */
   }
   .ldio-284ix4wfeaei div { box-sizing: content-box; }
   /* generated by https://loading.io/ */
</style>
<!-- begin::Body -->
<body class="kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed kt-header-mobile--fixed kt-subheader--enabled kt-subheader--transparent kt-aside--enabled kt-aside--fixed">
   <!-- begin:: Page -->
   <!-- begin:: Header Mobile -->
   <div id="kt_header_mobile" class="kt-header-mobile  kt-header-mobile--fixed ">
      <div class="kt-header-mobile__logo">
         <a href="index.html">
         <img alt="Logo" src="../assets/media/logos/logo-light.png" />
         </a>
      </div>
      <div class="kt-header-mobile__toolbar">
         <button class="kt-header-mobile__toggler kt-header-mobile__toggler--left" id="kt_aside_mobile_toggler"><span></span></button>
         <button class="kt-header-mobile__toggler" id="kt_header_mobile_toggler"><span></span></button>
         <button class="kt-header-mobile__topbar-toggler" id="kt_header_mobile_topbar_toggler"><i class="flaticon-more"></i></button>
      </div>
   </div>
   <!-- end:: Header Mobile -->
   <div class="kt-grid kt-grid--hor kt-grid--root">
   <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver kt-page">
   @include('layouts.backend.sidebar')
   <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-wrapper" id="kt_wrapper">
      @include('layouts.backend.header_top')
      <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor mt-5">
         <!-- begin:: Content -->
         <!-- begin:: Content -->
         <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid" id="kt_content">
            <div class="kt-portlet">
               <div class="kt-portlet__body">
                  <div class="kt-infobox">
                     <div class="kt-infobox__body">
                        <div class="row">
                           <div class="col-6">
                              <p><b>Patient Name:</b> {{$appointment->patient_name}}</p>
                              <p><b>Phone Number:</b> {{$appointment->patient_number}}</p>
                           </div>
                           <div class="col-6">
                              <p><b>Appointment Date:</b> {{date('d M Y', strtotime($appointment->appointment_date))}}</p>
                              <p><b>Time Slot:</b> <span class="kt-badge kt-badge--brand kt-badge--inline kt-badge--pill kt-badge--rounded">{{date('h:i a', strtotime($appointment->time_slot))}}</span></p>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <div class="kt-portlet kt-portlet--mobile">
               <div class="kt-portlet__head">
                  <div class="kt-portlet__head-label">
                     <span class="kt-portlet__head-icon">
                     <i class="kt-font-brand fa fa-star"></i>
                     </span>
                     <h3 class="kt-portlet__head-title">
                        Change Appointment Settings
                     </h3>
                  </div>
               </div>
               <form class="kt-form" action="/account/hospital/appointment/changesettings/{{$appointment->id}}" method="post" id="appointment_settings">
                  @csrf               
                    <div class="kt-portlet__body">
                        <div class="form-group">
                            <label>Appointment Status</label><br>
                            <select class="form-control m-select2 change_status" id="kt_select2_1" name="status" style="width: 100%;">
                              <option value="Pending" {{$appointment->status == "Pending" ? "Selected" : ''}}>Pending</option>
                              <option value="On-hold" {{$appointment->status == "On-hold" ? "Selected" : ''}}>On-hold</option>
                              <option value="Approved" {{$appointment->status == "Approved" ? "Selected" : ''}}>Approved</option>
                              <option value="Approved" {{$appointment->status == "Cancelled" ? "Selected" : ''}}>Cancelled</option>
                              <option value="Approved" {{$appointment->status == "Treated" ? "Selected" : ''}}>Treated</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Amount Payable</label>
                            <input type="number" class="form-control" name="payable_amount" id="payable_amount" value="{{$appointment != null ? $appointment->payable_amount: ''}}"/>
                        </div>
                        <div class="form-group">
                            <label>Amount Paid</label>
                            <input class="form-control" type="number" name="paid_amount" id="paid_amount" value="{{$appointment_payment != null ? $appointment_payment->paid_amount: ''}}">
                        </div>
                        <div class="form-group">
                            <label>Cashback Amount</label>
                            <input class="form-control" type="number" name="cashback1" value="0.0" id="cashback1" value="{{$appointment_payment != null ? $appointment_payment->cashback : ''}}">
                        </div>
                        <div class="form-group">
                            <label>Weight</label>
                            <input type="text" class="form-control" name="weight" id="weight" value="{{$appointment->weight}}"/>
                        </div>
                        <div class="form-group">
                            <label>Blood Pressure</label>
                            <input type="text" class="form-control" name="blood_pressure" id="blood_pressure" value="{{$appointment->blood_pressure}}"/>
                        </div>
                        <div class="form-group">
                            <label>Diabetes</label>
                            <input type="text" class="form-control" name="diabetes" id="diabetes" value="{{$appointment->diabetes}}"/>
                        </div>
                        <input class="form-control" type="hidden" name="cashback" id="cashback">
                    </div>
                    <div class="kt-portlet__foot kt-portlet__foot--solid">
                        <div class="kt-form__actions">
                            <div class="row">
                                <div class="col-12">
                                    <button type="submit" class="btn btn-brand"><i class="fa fa-paper-plane"></i> Save Changes</button>
                                </div>
                            </div>
                        </div>
                    </div>
            </form>
            <div class="kt-portlet__body kt-portlet__body--fit">
               <!--begin: Datatable -->
               <!--end: Datatable -->
            </div>
         </div>
      </div>
      <!-- end:: Content -->
      <!-- end:: Content -->
   </div>
   <script>
      $(document).ready(function(){
         if($('.change_status').val() != "Approved"){
            $("#payable_amount").attr('disabled','disabled');
            $("#paid_amount").attr('disabled','disabled');
         }

         $("#cashback1").attr('disabled','disabled');
         var payable_amount = 0;
         var paid_amount = 0;
         $("#payable_amount").on("paste keyup", function() {
            payable_amount = $(this).val();
            $('#cashback').val(paid_amount - payable_amount);
            $('#cashback1').val(paid_amount - payable_amount);
         });

         $('.change_status').on('change', function() {
            if(this.value == "Approved"){
               $("#payable_amount").removeAttr('disabled');
               $("#paid_amount").removeAttr('disabled');
            }else{
               $("#payable_amount").attr('disabled','disabled');
               $("#paid_amount").attr('disabled','disabled');
            }
         });

         $("#paid_amount").on("paste keyup", function() {
            paid_amount = $(this).val(); 
            $('#cashback').val(paid_amount - payable_amount);
            $('#cashback1').val(paid_amount - payable_amount);
         });
      });
   </script>
   @endsection