@extends('layouts.backend.layout')
@section('content')

<style type="text/css">
@keyframes ldio-284ix4wfeaei {
  0% { opacity: 1 }
  50% { opacity: .5 }
  100% { opacity: 1 }
}
.ldio-284ix4wfeaei div {
  position: absolute;
  width: 10px;
  height: 40px;
  top: 30px;
  animation: ldio-284ix4wfeaei 1s cubic-bezier(0.5,0,0.5,1) infinite;
}.ldio-284ix4wfeaei div:nth-child(1) {
  transform: translate(15px,0);
  background: #e15b64;
  animation-delay: -0.6s;
}.ldio-284ix4wfeaei div:nth-child(2) {
  transform: translate(35px,0);
  background: #f47e60;
  animation-delay: -0.4s;
}.ldio-284ix4wfeaei div:nth-child(3) {
  transform: translate(55px,0);
  background: #f8b26a;
  animation-delay: -0.2s;
}.ldio-284ix4wfeaei div:nth-child(4) {
  transform: translate(75px,0);
  background: #abbd81;
  animation-delay: -1s;
}
.loadingio-spinner-bars-whv1n2lzl1 {
  width: 41px;
  height: 41px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-284ix4wfeaei {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.41);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-284ix4wfeaei div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
<!-- begin::Body -->
<body class="kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed kt-header-mobile--fixed kt-subheader--enabled kt-subheader--transparent kt-aside--enabled kt-aside--fixed">
   <!-- begin:: Page -->
   <!-- begin:: Header Mobile -->
   <div id="kt_header_mobile" class="kt-header-mobile  kt-header-mobile--fixed ">
      <div class="kt-header-mobile__logo">
         <a href="index.html">
         <img alt="Logo" src="../assets/media/logos/logo-light.png" />
         </a>
      </div>
      <div class="kt-header-mobile__toolbar">
         <button class="kt-header-mobile__toggler kt-header-mobile__toggler--left" id="kt_aside_mobile_toggler"><span></span></button>
         <button class="kt-header-mobile__toggler" id="kt_header_mobile_toggler"><span></span></button>
         <button class="kt-header-mobile__topbar-toggler" id="kt_header_mobile_topbar_toggler"><i class="flaticon-more"></i></button>
      </div>
   </div>
   <!-- end:: Header Mobile -->
   <div class="kt-grid kt-grid--hor kt-grid--root">
   <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver kt-page">
   @include('layouts.backend.sidebar')
   <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-wrapper" id="kt_wrapper">
   @include('layouts.backend.header_top')
   <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor mt-5">
      <!-- begin:: Content -->
      <!-- begin:: Content -->
      <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid" id="kt_content">
         <div class="kt-portlet kt-portlet--mobile">
            <div class="kt-portlet__head">
               <div class="kt-portlet__head-label">
                  <span class="kt-portlet__head-icon">
                  <i class="kt-font-brand fa fa-star"></i>
                  </span>
                  <h3 class="kt-portlet__head-title">
                     Add New Report
                  </h3>
               </div>
            </div>
            <form class="kt-form" action="/account/lab/report/create" method="post">
               @csrf
               <div class="kt-portlet__body">
                  <div class="form-group">
                        <label>Templates</label><br>
                        <select class="form-control m-select2" onChange="loadTemplate()" id="kt_select2_4" name="template_id" style="width: 100%;">
                           <option value="0" selected>Choose Report Template</option>
                           @foreach($templates as $template)
                           <option value="{{$template->id}}">{{$template->name}}</option>
                           @endforeach
                        </select>
                  </div>

                  <div class="form-group">
                        <label>Ref By Doctor</label><br>
                        <select class="form-control m-select2" id="kt_select2_2" name="doctor_id" style="width: 100%;">
                           <option value="0">Refered By.</option>
                           @foreach(Auth::user()->clinic->doctors as $doctor)
                           <option value="{{$doctor->doctor->id}}">{{$doctor->doctor->name}}</option>
                           @endforeach
                        </select>
                  </div>
                  <div class="form-group">
                     <label>Date</label>
                     <input type="text" class="form-control" id="kt_datepicker_1" readonly placeholder="Select Report Date" name="date"/>
                  </div>
                  
                  <div class="form-group ">
                     <label>Patient Phone Number</label>
                     <input  type="text" class=" form-control" placeholder="Enter Patient's Phone Number" id="patient_number" name="patient_number">
                  </div>
                  <div class="form-group" id="load_data">
                     <button type="button" class="btn btn-success btn-sm" onclick="loadData()">Load Data</button>
                  </div>
                  <div class="loading_data" style=" position: relative; ">
                     <!-- Spinner  -->
                     <div class="loadingio-spinner-bars-whv1n2lzl1"><div class="ldio-284ix4wfeaei">
                     <div></div><div></div><div></div><div></div>
                     </div></div>
                     <!-- Spinner  -->
                     <span style=" position: absolute; top: 10px; left: 50px; font-weight: bold; ">Loading Patient Data...</span>
                  </div>
                  <div class="form-group " id="name_field">
                     <label>Patient Name</label>
                     <input   type="text" class=" form-control" placeholder="Enter Patient's Name" id="patient_name" name="patient_name" >
                  </div>
                  
               <input type="hidden" class="form-control" id="patient_id" name="patient_id">

               <div class="form-group">
                  <label>Report</label>
                  <textarea id="report_content" class="form-control @error('report') is-invalid @enderror" name="report">{{ old('report') }}</textarea>
                  @error('report')
                     <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                     </span>
                  @enderror
               </div>
               <script>
                  CKEDITOR.replace( 'report' );
               </script>

               <div class="kt-portlet__foot kt-portlet__foot--solid">
                  <div class="kt-form__actions">
                     <div class="row">
                        <div class="col-12">
                           <button type="submit" class="btn btn-brand"><i class="fa fa-paper-plane"></i> Submit</button>
                        </div>
                     </div>
                  </div>
               </div>
            </form>
            <div class="kt-portlet__body kt-portlet__body--fit">
               <!--begin: Datatable -->
               <!--end: Datatable -->
            </div>
         </div>
      </div>
      <!-- end:: Content -->
      <!-- end:: Content -->
   </div>
   <script>
      var $input = $('#patient_number');
      $('#name_field').hide();
      $('.loading_data').hide();
      $("#load_data").hide();
      $input.keydown(function () {
         $("#load_data").show();
         $('.loading_data').hide();
         $('#name_field').hide();
      });

      function loadData(){
         $("#load_data").hide();
         $('#name_field').hide();
         $('.loading_data').show();
         $.ajax({
            type:'POST',
            url:'/account/appointment/get_patient_record',
            data: {_token: '<?php echo csrf_token() ?>', patient_number: $input.val()},
            dataType : 'json',
            success:function(data) {
               setTimeout(
                  function() 
                  {
                     $('.loading_data').hide();
                     $('#patient_name').val(data.patient_name);
                     $('#patient_id').val(data.patient_id);
                     $('#name_field').show();
                  }, 500
               );
            }
         });
      }
   </script>

   <script>
      function loadTemplate(){
         var value = $('select[name="template_id"]').val();
         var content = CKEDITOR.instances['report_content'];
         if(value == 0){
            content.setData("<p></p>");
         }else{
            $.ajax({
               type:'POST',
               url:'/account/get_report_template',
               data: {_token: '<?php echo csrf_token() ?>', template_id: value},
               dataType : 'json',
               success:function(data) {
                  content.setData(data.template);
               }
            });
            }
      }
   </script>
   @endsection
